print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "D:/GitHubRepos/sgu-final-build/Assets/Models/Maya/Corridor_Chunk_3_45Degree.mb"`)
{		
	file -o "D:/GitHubRepos/sgu-final-build/Assets/Models/Maya/Corridor_Chunk_3_45Degree.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "D:/GitHubRepos/sgu-final-build/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";

sysFile -delete "D:/GitHubRepos/sgu-final-build/Temp/CommandPipe";

$donepipeKill = `fopen "D:/GitHubRepos/sgu-final-build/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
